############################################################
# Dockerfile to install maya2018
# Based on nvidia/base:centos7-usd-0.8

FROM usd-docker/pixar-usd-monolithic:latest-centos7

##ARG current_host_ip_address
ARG usd_version
ARG maya_version
ENV USD_VERSION=usd_version

LABEL maya.version="${maya_version}.0" maintainer="Animal Logic"

ENV MAYA_LOCATION=$BUILD_DIR/maya${maya_version}DevKit

ENV MAYA_LIBRARY_DIR=$BUILD_DIR/maya${maya_version}DevKit
ENV MAYA_INCLUDE_DIR=$BUILD_DIR/maya${maya_version}DevKit/include

##ENV HTTP_HOSTNAME=$current_host_ip_address
ENV MAYA_EXECUTABLE=$MAYA_LOCATION/bin/maya
ENV MAYA_PYTHON_EXECUTABLE=$MAYA_LOCATION/bin/mayapy
ENV MAYA_MAJOR_VERSION="${maya_version}"

COPY downloads/maya-usd-master.zip $DOWNLOADS_DIR/


#########################
## BUILD autodesk usd plugin

ENV USD_MAYA_BUILD_DIR=$BUILD_DIR/maya_usd/${USD_VERSION}_maya${maya_version}
ENV USD_MAYA_INSTALL_DIR=$BUILD_DIR/maya_usd/${USD_VERSION}_maya${maya_version}/install


RUN mkdir -p ${USD_MAYA_BUILD_DIR} && \
    mkdir -p ${USD_MAYA_INSTALL_DIR}


ENV USD_LIBRARY=${USD_BUILD_DIR}/lib:${USD_BUILD_DIR}/build/USD-${USD_VERSION}/pxr/base/lib/
ENV USD_LIBRARY_ROOT=${USD_BUILD_DIR}/build/USD-${USD_VERSION}


#########################
# Install Ninja Generator
RUN cd /tmp && \
    git clone git://github.com/ninja-build/ninja.git && cd ninja && \
    git checkout release && \
    ./configure.py --bootstrap
    
ENV NINJA=/tmp/ninja/ninja
    
RUN unzip $DOWNLOADS_DIR/maya-usd-master.zip -d $TMP_DIR
    
RUN cd $TMP_DIR/maya-usd-master && \
	python build.py \
	-v 3 \
	--generator Ninja \
    --build-args="-DCMAKE_MAKE_PROGRAM=${NINJA},-DPXR_BUILD_MONOLITHIC=ON" \
    --maya-location ${MAYA_LOCATION} \
    --devkit-location ${MAYA_LOCATION}  \
    --pxrusd-location ${USD_BUILD_DIR} \
    --install-location ${USD_MAYA_INSTALL_DIR} \
    ${USD_MAYA_BUILD_DIR}
    
#ENV USD_INSTALL_ROOT=${USD_BUILD_DIR}
#ENV USD_CONFIG_FILE=$USD_INSTALL_ROOT/pxrConfig.cmake
#ENV PATH=$PATH:$USD_INSTALL_ROOT/bin
#ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$USD_INSTALL_ROOT/lib
#ENV PYTHONPATH=$PYTHONPATH:$USD_INSTALL_ROOT/lib/python